generators:

  iron-limit: 75
  gold-limit: 25
  diamond-limit: 8
  emerald-limit: 5
  netherstar-limit: 2


  #spawn each x ticks (20t -> 1s)
  iron-between-1: 12 #level 1
  iron-between-2: 10 #level 2
  iron-between-3: 8 #level 3
  gold-between-1: 25 #level 1
  gold-between-2: 20 #level 2
  gold-between-3: 15 #level 3

  #spawn each x seconds
  diamond-between-1: 8 #level 1
  diamond-between-2: 5 #level 2
  diamond-between-3: 5 #level 3
  emerald-between-1: 25 #level 1
  emerald-between-2: 17 #level 2
  emerald-between-3: 12 #level 3

  #upgrade after x seconds
  diamond-upgrade-1: 300 #seconds to level 1
  diamond-upgrade-2: 300 #seconds to level 2
  emerald-upgrade-1: 420 #seconds to level 1
  emerald-upgrade-2: 420 #seconds to level 2

shop:

  DIAMOND_SWORD: 3
  TNT: 8
  WATER_BUCKET: 6
  SPONGE: 6

upgrades:

  SHARPNESS: 8
  PROTECTION-1: 5
  PROTECTION-2: 10
  PROTECTION-3: 20
  PROTECTION-4: 30
  HASTE-1: 4
  HASTE-2: 6
  FORGE-2: 4
  FORGE-3: 8
  FORGE-4: 12
  HEAL_POOL: 3